// user

export const LOGIN_USER = 'LOGIN_USER'

// degrees

export const FETCH_DEGREES = 'FETCH_DEGREES'
export const RECEIVE_DEGREES = 'RECEIVE_DEGREES'
export const UNIQUE_DEGREES = 'UNIQUE_DEGREES'

// jobs

export const FETCH_JOBS = 'FETCH_JOBS'
export const FILTERED_JOBS = 'FILTERED_JOBS'
export const RECEIVE_JOBS = 'RECEIVE_JOBS'

// job types

export const ADD_SELECTED_JOB_TYPES = 'ADD_SELECTED_JOB_TYPES'
export const INCLUDE_JOB_BY_JOB_TYPE = 'INCLUDE_JOB_BY_JOB_TYPE'
export const UNIQUE_JOB_TYPES = 'UNIQUE_JOB_TYPES'

// organizations

export const ADD_SELECTED_ORGANIZATIONS = 'ADD_SELECTED_ORGANIZATIONS'
export const INCLUDE_JOB_BY_ORGANIZATION = 'INCLUDE_JOB_BY_ORGANIZATION'
export const UNIQUE_ORGANIZATIONS = 'UNIQUE_ORGANIZATIONS'
