// user
export const LOGIN_USER = 'LOGIN_USER'

// jobs
export const FETCH_JOBS = 'FETCH_JOBS'
export const RECEIVE_JOBS = 'RECEIVE_JOBS'

// job types
export const ADD_SELECTED_JOB_TYPES = 'ADD_SELECTED_JOB_TYPES'

// organizations
export const ADD_SELECTED_ORGANIZATIONS = 'ADD_SELECTED_ORGANIZATIONS'
export const FILTERED_JOBS_BY_ORGANIZATIONS = 'FILTERED_JOBS_BY_ORGANIZATIONS'
export const UNIQUE_ORGANIZATIONS = 'UNIQUE_ORGANIZATIONS'
